name: Alive
on:
  schedule:
    - cron: "6 0 * * *"

jobs:
  cronjob-based-github-action:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
